### ISSUE TITLE
Invalid Instructions to install the agent on multiple EC2 instances using the Systems Manager

### ISSUE THREAD

**Issue by h3ct0rjs** [awsdocs/amazon-inspector-user-guide#10]
Hi Guys, 

Hope you're doing well, recently at my company with need to do a security assessment using aws inspector, after checking the current  documentation [1]  I noticed that you have out of date the section how ***To install the agent on multiple EC2 instances using the Systems Manager Run Command***

If you need any help updating this, I'll be happy. 

Thanks in advace, 
Sincerely, 
Hector F. 
[1] https://docs.aws.amazon.com/inspector/latest/userguide/inspector_installing-uninstalling-agents.html

**Comment by jmanwiller** [comment]
Hi Hector,

Can you provide more detail on what is out of date, so that I can verify the proposed updates with the service team?

I will also reach out to them to see if they can identify anything that is currently out of date.

After I establish the required updates, I can then update the guide on the main AWS documentation site and then port those changes to the GitHub repository.

Thanks,

Janice

**Comment by h3ct0rjs** [comment]
Hi @jmanwiller,

Sure I'll try to provide you all the details. First If you take a look in the link above [1] you will notice  the section (**To install the agent on multiple EC2 instances using the Systems Manager Run Command**), there is a set of steps to be taken, but when you check point **2.**,  this instruction says : 

> In the navigation pane under Systems Manager Services, choose Run Command...

But this doesn't exist anymore in https://console.aws.amazon.com/ec2/, if you go to your aws console home https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#Home:  you will see that there is not shortcut to open systems manager. 

Currently if you want to open  Systems Manager, you'll need to search the service. 
So thats why I say that this is not updated. 

Thanks in advanced,
Sincerely, 
Hector F, 
Colombia

**Comment by jmanwiller** [comment]
Thanks for the clarification. I've passed that along to the service team.

**Comment by h3ct0rjs** [comment]
Okay @jmanwiller , thank you very much for your help

**Comment by jmanwiller** [comment]
The updates are complete.

**Comment by h3ct0rjs** [comment]
That's it, thank you very Much, one last question. 
What's the best way to suggest a few changes in the aws inspector service, is there any official link or something like that. 

Thank you very much, 
Sincerely, 
Hector F.

**Comment by jmanwiller** [comment]
There isn't an official link. If you provide your suggestions to me, I'll pass them along to the service team.

**Comment by h3ct0rjs** [comment]
Thank you very much. 

Regards, 
Hector F.
