### ISSUE TITLE
CloudWatch Events Format missing

### ISSUE THREAD

**Issue by peteroruba** [awsdocs/amazon-inspector-user-guide#13]
Hello
In order let Inspector Findings trigger further processing an integration with CloudWatch Events would be needed. This requires to filter on particular severities or event types. However, the CloudWatch Events format emitted by Inspector is not documented.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
