### ISSUE TITLE
Invalid Instructions for Setting up SNS Topic 

### ISSUE THREAD

**Issue by platform9-34th** [awsdocs/amazon-inspector-user-guide#8]
Section [Setting Up an SNS Topic for Amazon Inspector Notifications](https://docs.aws.amazon.com/inspector/latest/userguide/inspector_assessments.html#sns-topic) of [Amazon Inspector Assessment Templates and Assessment Runs](https://docs.aws.amazon.com/inspector/latest/userguide/inspector_assessments.html) contains outdated steps for modifying the permissions of an existing SNS Topic.

I'm not sure when this happened, but the SNS console has a new interface and none of the items listed existing anymore.  I suspect we need append an IAM JSON policy directly to the topic but it's not clear how and what the policy needs to look like.  So I'm unable to use SNS Topic with the Inspector service at this point in time.

**Comment by platform9-34th** [comment]
Hi team, it's been nearly 6 months since this issue was reported.  Any plans on fixing this?

**Comment by jmanwiller** [comment]
I started working on the Inspector documentation relatively recently. I'll coordinate with the service team for details on the required updates.

**Comment by jmanwiller** [comment]
So the service team did take a look, and the instructions are for creating a new SNS topic, not for modifying an existing SNS topic. The UIs for creating and editing SNS topics are apparently very different. To determine what would need to be updated in an existing topic, they suggest creating a new SNS topic and then comparing the access policy documents.
