### ISSUE TITLE
Release Notes of Inspector Agent

### ISSUE THREAD

**Issue by platform9-34th** [awsdocs/amazon-inspector-user-guide#9]
Please correct me if I'm wrong, but it does not appear there are release notes for updates made to the Inspector agent.  For what it's worth I expected to find a link under section [Amazon Inspector Agent Updates](https://docs.aws.amazon.com/inspector/latest/userguide/inspector_agents.html#agent-updates) in [Amazon Inspector Agents](https://docs.aws.amazon.com/inspector/latest/userguide/inspector_agents.html).

If there is no release notes made public to customers I find this troubling.  The Inspector service was [released back in 2015](https://aws.amazon.com/about-aws/whats-new/2015/10/announcing-amazon-inspector/).  Other AWS services like Systems Manager [publicly document updates to their SSM agent](https://github.com/aws/amazon-ssm-agent/blob/master/RELEASENOTES.md).  Heck, Systems Manger team went the extra mile and [publish updates to SNS when new agent versions are released](https://docs.aws.amazon.com/systems-manager/latest/userguide/ssm-agent-subscribe-notifications.html).

**Comment by davlaur** [comment]
Hello there,

Thank you for raising this issue.

The best place to see what updates have been made to Inspector (and the agent) is through the official [AWS What's New](https://aws.amazon.com/new/?whats-new-content-all.sort-by=item.additionalFields.postDateTime&whats-new-content-all.sort-order=desc&awsf.whats-new-security-id-compliance=general-products%23amazon-inspector) feed filtered by Security, Identification, and Compliance, and then Inspector.  
You can also find major changes that required documentation updates on the [documentation history](https://docs.aws.amazon.com/inspector/latest/userguide/document-history.html) page of the Inspector Docs.  
Both option of these options provide RSS feeds.  Please note, the What's New feed includes more detailed explanations of each updates but it's RSS feed does not allow you to filter by service.

Unfortunately, the github documentation is not automatically updated when there are changes to the web documentation, but I have put in a request to get it updated asap.

I hope this helps!
